"""inital schema

Revision ID: 5fc3537d31f7
Revises: 
Create Date: 2026-01-31 18:38:08.243033

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = '5fc3537d31f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'analysis_usage' not in existing_tables:
        op.create_table(
            'analysis_usage',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('session_id', sa.String(length=36), nullable=True),
            sa.Column('ip_address', sa.String(length=64), nullable=True),
            sa.Column('month_key', sa.String(length=16), nullable=False),
            sa.Column('count', sa.Integer(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'companies' not in existing_tables:
        op.create_table(
            'companies',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('name', sa.String(length=128), nullable=False),
            sa.Column('website', sa.String(length=256), nullable=True),
            sa.Column('greenhouse_token', sa.String(length=128), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'cover_letter_documents' not in existing_tables:
        op.create_table(
            'cover_letter_documents',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('session_id', sa.String(length=36), nullable=False),
            sa.Column('job_id', sa.String(length=64), nullable=False),
            sa.Column('draft_content', sa.Text(), nullable=False),
            sa.Column('current_version_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(
            op.f('ix_cover_letter_documents_job_id'),
            'cover_letter_documents',
            ['job_id'],
            unique=False,
        )
        op.create_index(
            op.f('ix_cover_letter_documents_session_id'),
            'cover_letter_documents',
            ['session_id'],
            unique=False,
        )

    if 'deep_analysis' not in existing_tables:
        op.create_table(
            'deep_analysis',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('session_id', sa.String(length=36), nullable=False),
            sa.Column('job_id', sa.String(length=64), nullable=False),
            sa.Column('payload', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(
            op.f('ix_deep_analysis_job_id'),
            'deep_analysis',
            ['job_id'],
            unique=False,
        )
        op.create_index(
            op.f('ix_deep_analysis_session_id'),
            'deep_analysis',
            ['session_id'],
            unique=False,
        )

    if 'job_selections' not in existing_tables:
        op.create_table(
            'job_selections',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('session_id', sa.String(length=36), nullable=False),
            sa.Column('job_id', sa.String(length=64), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(
            op.f('ix_job_selections_session_id'),
            'job_selections',
            ['session_id'],
            unique=False,
        )

    if 'jobs' not in existing_tables:
        op.create_table(
            'jobs',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('company_id', sa.Integer(), nullable=True),
            sa.Column('company_name', sa.String(length=128), nullable=False),
            sa.Column('title', sa.String(length=256), nullable=False),
            sa.Column('location', sa.String(length=256), nullable=False),
            sa.Column('remote', sa.Boolean(), nullable=False),
            sa.Column('seniority', sa.String(length=64), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('pay_ranges', sa.JSON(), nullable=False),
            sa.Column('source', sa.String(length=32), nullable=False),
            sa.Column('source_job_id', sa.String(length=128), nullable=False),
            sa.Column('apply_url', sa.String(length=512), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'sessions' not in existing_tables:
        op.create_table(
            'sessions',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('resume_text', sa.Text(), nullable=False),
            sa.Column('resume_s3_key', sa.String(length=512), nullable=True),
            sa.Column('extracted_skills', sa.JSON(), nullable=False),
            sa.Column('inferred_titles', sa.JSON(), nullable=False),
            sa.Column('seniority', sa.String(length=32), nullable=False),
            sa.Column('years_experience', sa.Integer(), nullable=False),
            sa.Column('location_pref', sa.String(length=128), nullable=True),
            sa.Column('remote_pref', sa.Boolean(), nullable=True),
            sa.Column('llm_summary', sa.Text(), nullable=True),
            sa.Column('first_name', sa.String(length=64), nullable=True),
            sa.Column('last_name', sa.String(length=64), nullable=True),
            sa.Column('email', sa.String(length=128), nullable=True),
            sa.Column('phone', sa.String(length=64), nullable=True),
            sa.Column('location', sa.String(length=128), nullable=True),
            sa.Column('social_links', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('daily_selections', sa.Integer(), nullable=False),
            sa.Column('daily_selection_date', sa.String(length=32), nullable=True),
            sa.Column('plan', sa.String(length=16), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'cover_letter_versions' not in existing_tables:
        op.create_table(
            'cover_letter_versions',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('document_id', sa.Integer(), nullable=False),
            sa.Column('session_id', sa.String(length=36), nullable=False),
            sa.Column('job_id', sa.String(length=64), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('created_by', sa.String(length=32), nullable=False),
            sa.Column('intent', sa.String(length=32), nullable=True),
            sa.Column('base_hash', sa.String(length=64), nullable=True),
            sa.Column('result_hash', sa.String(length=64), nullable=True),
            sa.ForeignKeyConstraint(['document_id'], ['cover_letter_documents.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(
            op.f('ix_cover_letter_versions_document_id'),
            'cover_letter_versions',
            ['document_id'],
            unique=False,
        )
        op.create_index(
            op.f('ix_cover_letter_versions_job_id'),
            'cover_letter_versions',
            ['job_id'],
            unique=False,
        )
        op.create_index(
            op.f('ix_cover_letter_versions_session_id'),
            'cover_letter_versions',
            ['session_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letter_versions_session_id'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_job_id'), table_name='cover_letter_versions')
    op.drop_index(op.f('ix_cover_letter_versions_document_id'), table_name='cover_letter_versions')
    op.drop_table('cover_letter_versions')
    op.drop_table('sessions')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_selections_session_id'), table_name='job_selections')
    op.drop_table('job_selections')
    op.drop_index(op.f('ix_deep_analysis_session_id'), table_name='deep_analysis')
    op.drop_index(op.f('ix_deep_analysis_job_id'), table_name='deep_analysis')
    op.drop_table('deep_analysis')
    op.drop_index(op.f('ix_cover_letter_documents_session_id'), table_name='cover_letter_documents')
    op.drop_index(op.f('ix_cover_letter_documents_job_id'), table_name='cover_letter_documents')
    op.drop_table('cover_letter_documents')
    op.drop_table('companies')
    op.drop_table('analysis_usage')
    # ### end Alembic commands ###
